import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * `docs/` の構造からそのまま作る。
 *
 * **手で並べない。** 401 本あり、本家の並び順は private 側にしか無い。
 * ディレクトリ構造は mirror にそのまま入っているので、そちらを信じる。
 * 本家と順序が違う箇所は出るが、**読めることが目的**で、複製ではない。
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
